vim.keymap.set( "n", "<leader>pv", vim.cmd.NvimTreeToggle, { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>rn", ":IncRename ", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>pm", ":Mason<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<A-h>", "<<", { noremap = true, silent = true })
vim.keymap.set( "n", "<A-l>", ">>", { noremap = true, silent = true })
vim.keymap.set( {"n","v"}, "<leader>t-", ":NvimTreeResize -5<CR>", { noremap = true, silent = true })
vim.keymap.set( {"n","v"}, "<leader>t+", ":NvimTreeResize +5<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>ss", ":sp<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>sv", ":vsp<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>wc", ":close<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>wh", ":wincmd h<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>wj", ":wincmd j<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>wk", ":wincmd k<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>wl", ":wincmd l<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>rn", vim.lsp.buf.rename, { noremap = true, silent = true })
vim.keymap.set( {"n", "v"}, "G", "Gzz", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>pl", ":Lazy<CR>", { noremap = true, silent = true })
vim.keymap.set( {"n", "x"}, "<A-j>", "<Cmd>MultipleCursorsAddDown<CR>", { noremap = true, silent = true })
vim.keymap.set( {"n", "x"}, "<A-k>", "<Cmd>MultipleCursorsAddUp<CR>", { noremap = true, silent = true })
vim.keymap.set( {"n", "x"}, "<C-LeftMouse>", "<Cmd>MultipleCursorsMouseAddDelete<CR>", { noremap = true, silent = true })
vim.keymap.set( {"n", "x"}, "<leader>cm", "<Cmd>MultipleCursorsAddMatches<CR>", { noremap = true, silent = true })
vim.keymap.set( {"n", "x"}, "<leader>cM", "<Cmd>MultipleCursorsAddMatchesV<CR>", { noremap = true, silent = true })
vim.keymap.set( {"n", "x"}, "<leader>cd", "<Cmd>MultipleCursorsAddJumpNextMatch<CR>", { noremap = true, silent = true })
vim.keymap.set( {"n", "x"}, "<leader>cD", "<Cmd>MultipleCursorsJumpNextMatch<CR>", { noremap = true, silent = true })
vim.keymap.set( {"n", "x"}, "<leader>cl", "<Cmd>MultipleCursorsLock<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>da", "GVggd", { noremap = true, silent = true })
vim.keymap.set( {"n", "v"}, "<leader>sa", "ggVG", { noremap = true, silent = true })
vim.keymap.set( "n", "yy",'V"+y', { noremap = true, silent = true })
vim.keymap.set( "v", "y",'"+y', { noremap = true, silent = true })
vim.keymap.set( "n", "P", "Vp", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>ca", ":CondaActivate<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>ht", ":HexToggle<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>mdt", "<Plug>MarkdownPreviewToggle", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>sf", "<cmd>Navbuddy<CR>", { noremap = true, silent = true })
vim.keymap.set( "n", "<leader>nd", "<cmd>Noice dismiss<CR>" ,{ noremap = true, silent = true })
