vim.keymap.set( "n", "<leader>pv",vim.cmd.NvimTreeToggle)
vim.keymap.set( "n", "<leader>rn", ":IncRename ")
vim.keymap.set( "n", "<leader>pm", ":Mason<CR>")
vim.keymap.set( "n", "<A-h>", "<<")
vim.keymap.set( "n", "<A-l>", ">>")
vim.keymap.set( {"n","v"}, "<leader>t-", ":NvimTreeResize -5<CR>")
vim.keymap.set( {"n","v"}, "<leader>t+", ":NvimTreeResize +5<CR>")
vim.keymap.set( "n", "<leader>ss", ":sp<CR>")
vim.keymap.set( "n", "<leader>sv", ":vsp<CR>")
vim.keymap.set( "n", "<leader>wc", ":close<CR>")
vim.keymap.set( "n", "<leader>wh", ":wincmd h<CR>")
vim.keymap.set( "n", "<leader>wj", ":wincmd j<CR>")
vim.keymap.set( "n", "<leader>wk", ":wincmd k<CR>")
vim.keymap.set( "n", "<leader>wl", ":wincmd l<CR>")
vim.keymap.set( "n", "<leader>rn", vim.lsp.buf.rename, {})
vim.keymap.set( {"n", "v"}, "G", "Gzz")
vim.keymap.set( "n", "<leader>pl", ":Lazy<CR>")
vim.keymap.set( {"n", "x"}, "<A-j>", "<Cmd>MultipleCursorsAddDown<CR>")
vim.keymap.set( {"n", "x"}, "<A-k>", "<Cmd>MultipleCursorsAddUp<CR>")
vim.keymap.set( {"n", "x"}, "<C-LeftMouse>", "<Cmd>MultipleCursorsMouseAddDelete<CR>")
vim.keymap.set( {"n", "x"}, "<leader>cm", "<Cmd>MultipleCursorsAddMatches<CR>")
vim.keymap.set( {"n", "x"}, "<leader>cM", "<Cmd>MultipleCursorsAddMatchesV<CR>")
vim.keymap.set( {"n", "x"}, "<leader>cd", "<Cmd>MultipleCursorsAddJumpNextMatch<CR>")
vim.keymap.set( {"n", "x"}, "<leader>cD", "<Cmd>MultipleCursorsJumpNextMatch<CR>")
vim.keymap.set( {"n", "x"}, "<leader>cl", "<Cmd>MultipleCursorsLock<CR>")
vim.keymap.set( "n", "<leader>da", "GVggd")
vim.keymap.set( {"n", "v"}, "<leader>sa", "ggVG")
vim.keymap.set( "n", "yy",'V"+y')
vim.keymap.set( "v", "y",'"+y')
vim.keymap.set( "n", "P", "Vp")
vim.keymap.set( "n", "<leader>ca", ":CondaActivate<CR>")
vim.keymap.set( "n", "<leader>ht", ":HexToggle<CR>")
vim.keymap.set( "n", "<leader>mdt", "<Plug>MarkdownPreviewToggle")
vim.keymap.set( "n", "<leader>sf", "<cmd>Navbuddy<CR>")
vim.keymap.set( "n", "<leader>nd", "<cmd>Noice dismiss<CR>")
