vim.keymap.set("n", "<leader>rn", "<cmd>IncRename ", { noremap = true, silent = true })
-- vim.keymap.set("n", "<A-h>", "V<", { noremap = true, silent = true })
-- vim.keymap.set("n", "<A-l>", "V>", { noremap = true, silent = true })
-- vim.keymap.set("v", "<A-h>", "<", { noremap = true, silent = true })
-- vim.keymap.set("v", "<A-l>", ">", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>ss", ":sp<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>sv", ":vsp<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>wc", ":close<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>wh", ":wincmd h<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>wj", ":wincmd j<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>wk", ":wincmd k<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>wl", ":wincmd l<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename, { noremap = true, silent = true })
vim.keymap.set({ "n", "v" }, "G", "Gzz", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>pl", ":Lazy<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>da", "GVggd", { noremap = true, silent = true })
vim.keymap.set({ "n", "v" }, "<leader>sa", "ggVG", { noremap = true, silent = true })
vim.keymap.set("n", "yy", 'V"+y', { noremap = true, silent = true })
vim.keymap.set("v", "y", '"+y', { noremap = true, silent = true })
vim.keymap.set("n", "yiw", '"+yiw', { noremap = true, silent = true })
vim.keymap.set("n", "Y", 'v$"+y', { noremap = true, silent = true })
vim.keymap.set("n", "P", "Vp", { noremap = true, silent = true })
vim.keymap.set("n", "<M-bs>", "diw", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>it", ":InspectTree<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "gcp", "vipgc", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>a<CR>", "ggVG=", { noremap = true, silent = true })
vim.keymap.set('n', '<leader>tw', ':set wrap!<CR>', { noremap = true, silent = true })
